language: java

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: rdfvizler:JgRgpC8Qyis2rOvWmW8CIC5g